version: '3.9'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '3000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  redis:
    container_name: redisclz_container
    image: redis:alpine
    restart: always
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data

  postgres:
    container_name: postgresclz_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=task-chatter
      - POSTGRES_PASSWORD=task-chatter
      - POSTGRES_DB=task-chatter
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql
  app:
    build:
      context: .
      dockerfile: /Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - /.env
    volumes:
      - .:/user/src/app
